export component UserBar {
    in property <string> Name;
    in property <string> Status;
    in property <brush> Color;
    Rectangle {
        width: 100%;
        height: 36px;
        background: #211a67;
        Rectangle {
            x: 4px;
            width: 27px;
            height: 27px;
            border-radius: 27px;
            background: Color;
        }

        VerticalLayout {
            x: 36px;
            width: parent.width - 36px;
            spacing: 0px;
            Text {
                text: Name;
                font-family: "Noto Sans";
                font-weight: 550;
                font-size: 13px;
                overflow: TextOverflow.elide;
            }

            Text {
                text: Status;
                overflow: TextOverflow.elide;
                font-family: "Noto Sans";
                font-size: 11px;
                font-weight: 300;
            }
        }
    }
}