import { Button } from "std-widgets.slint";
export component Chat {
    in property <string> Name;
    in property <string> LastMessage;
    in property <int> Notifications;
    in property <bool> Active;
    in property <brush> Color;
    in property <int> id;
    callback clicked(string);
    Rectangle {
        x: 0px;
        height: 36px;
        width: parent.width;
        background: !Active ? (Notifications == 0 ? #112 : #224) : #336;
        Button {
            width: 100%;
            height: 100%;
            opacity: 0;
            clicked => {
                root.clicked(id);
            }
        }
        Rectangle {
            x: 4px;
            width: 27px;
            height: 27px;
            border-radius: 27px;
            background: Color;
        }

        VerticalLayout {
            x: 36px;
            width: parent.width - 60px + (Notifications == 0 ? 30px : 0px);
            spacing: 0px;
            Text {
                text: Name;
                font-family: "Noto Sans";
                font-weight: 550;
                font-size: 13px;
                overflow: TextOverflow.elide;
            }

            Text {
                text: LastMessage;
                font-family: "Noto Sans";
                font-size: 11px;
                font-weight: 300;
                overflow: TextOverflow.elide;
            }
        }

        Rectangle {
            visible: Notifications > 0;
            x: parent.width - 22px;
            width: 18px;
            height: 18px;
            border-radius: 18px;
            background: #f55;
            Text {
                text: Notifications;
            }
        }
    }
}