// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
export type Channel = {
  creator: Identity,
  name: string,
  id: string,
  created: Timestamp,
  description: string | undefined,
  dm: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Channel {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("creator", AlgebraicType.createIdentityType()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("id", AlgebraicType.createStringType()),
      new ProductTypeElement("created", AlgebraicType.createTimestampType()),
      new ProductTypeElement("description", AlgebraicType.createOptionType(AlgebraicType.createStringType())),
      new ProductTypeElement("dm", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Channel): void {
    Channel.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Channel {
    return Channel.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


